README.rst

Use a literal block to highlight the `git clone` command.
Use inline literal markup to highlight the `SetpForDevelopment.sh` script.
Fix a typo (scipt->script).
Change-Id: I6f033154d2b60a2f19c6adf44b5aff24e4cf6ebe

DOC: Improve the README.rst code syntax.

---

src/Filtering/ImageStatistics/AdaptiveHistogramEqualizationImageFilter/Documentation.rst

In an attempt to add column headers, the previous commit (0ae9d60) seems
to have had undesired collateral effects and the images were no longer
being rendered.
Change-Id: I69dcdf4c0c83ae3c3f8ec86ffad84a91eb9ecc86

BUG: Fix the example images not being rendered.

---

Utilities/GitSetup/git-pr

The response can be:
{'message': "API rate limit exceeded for XXX.XXX.XXX.XXX. (But here's the good
news: Authenticated requests get a higher rate limit. Check out the
documentation for more details.)", 'documentation_url':
'https://developer.github.com/v3/#rate-limiting'}

BUG: Fail gracefully in git-pr with too many requests

---

Utilities/GitSetup/git-review-push

GitHub now provides a similar server-side hook with a link to open the
PR.

ENH: Remove pull request preview link for git review-push

---

src/Core/Common/DistanceBetweenPoints/Code.cxx

Support for vnl_math_abs has been removed in ITK 5.

COMP: Replace vnl_math_abs with std::abs

---

Documentation/Build/index.rst

ITKApps primary repository is now hosted on github.
Related to issue #94

ENH: Update ITKApps reference to new address

---

src/Filtering/Thresholding/CMakeLists.txt

Re-enable Otsu thresholding baseline test.
Fixes #75.

ENH: Re-enable Otsu baseline test

---

src/Segmentation/Watersheds/SegmentWithWatershedImageFilter/Code.cxx

This class has been deprecated in ITK 5.0 in favor of CastImageFilter.

BUG: Remove unused VectorCastImageFilter include

---

src/Compatibility/Deprecated/ResampleRGBImage/Code.cxx
src/Core/Transform/ApplyAffineTransformFromHomogeneousMatrixAndResample/Code.cxx
src/Core/Transform/TranslateImage/Code.cxx
src/Filtering/AnisotropicSmoothing/ComputeCurvatureAnisotropicDiffusion/Code.cxx
src/Filtering/AnisotropicSmoothing/ComputeCurvatureFlow/Code.cxx
src/Filtering/AnisotropicSmoothing/ComputeGradientAnisotropicDiffusion/Code.cxx
src/Filtering/AnisotropicSmoothing/ComputePeronaMalikAnisotropicDiffusion/Code.cxx
src/Filtering/AntiAlias/SmoothBinaryImageBeforeSurfaceExtraction/Code.cxx
src/Filtering/FFT/FilterImageInFourierDomain/Code.cxx
src/Filtering/ImageFeature/DetectEdgesWithCannyFilter/Code.cxx
src/Filtering/ImageGradient/ComputeGradientMagnitudeRecursiveGaussian/Code.cxx
src/Filtering/ImageGrid/ChangeImageOriginSpacingOrDirection/Code.cxx
src/Filtering/ImageGrid/ResampleAnImage/Code.cxx
src/Filtering/ImageIntensity/ApplyExpNegativeImageFilter/Code.cxx
src/Filtering/ImageIntensity/ComputeSigmoid/Code.cxx
src/Filtering/ImageIntensity/MultiplyImageByScalar/Code.cxx
src/Filtering/ImageStatistics/AdaptiveHistogramEqualizationImageFilter/Code.cxx
src/Filtering/Smoothing/SmoothWithRecursiveGaussian/Code.cxx
src/Nonunit/Review/SegmentBloodVesselsWithMultiScaleHessianBasedMeasure/Code.cxx
src/Segmentation/LevelSets/SegmentWithGeodesicActiveContourLevelSet/Code.cxx
src/Segmentation/Watersheds/SegmentWithWatershedImageFilter/Code.cxx

The ato[if] functions do not provide mechanisms for distinguishing
between '0' and the error condion where the input can not be converted.
std::sto[id] provides exception handling and detects when an invalid
string attempts to be converted to an [integer|double].
ato[if]()
Con: No error handling.
Con: Handle neither hexadecimal nor octal.
The use of ato[if] in code can cause it to be subtly broken.
ato[if] makes two very big assumptions indeed:
The string represents an integer/floating point value.
The integer can fit into an int.

STYLE: Prefer error checked std::sto[id] over ato[if]

---

Utilities/GitSetup/config

Fixing the path for the GitSetup.git, as running SetupForDevelopment.sh failed to find the repository at the link specified.

BUG: Fix path for GitSetup.git

---

CMake/FindSphinx.cmake
Superbuild/External-Python.cmake

This ensures we have a new enough version of sphinx. The system version
on Ubuntu 18.04 yields:
Running Sphinx v1.6.7
Exception occurred:
File "/home/kitware/Dashboards/Tests/ITKExamples-doc-build/ITKEx-build/Utilities/SphinxExtensions/breathe/breathe/renderer/sphinxrenderer.py", line 89, in DomainDirectiveFactory
'union': (cpp.CPPUnionObject, 'union'),
AttributeError: module 'sphinx.domains.cpp' has no attribute 'CPPUnionObject'
xref https://github.com/sphinx-doc/sphinx/issues/6285

BUG: Use sphinx-build executable from Superbuild

---

Utilities/CookieCutter/{{cookiecutter.example_name}}/CMakeLists.txt
Utilities/CreateNewExample.py.in

This PR/commit will make the CreateNewExample script work with an existing ITK build. I could not get documentation built, but it the instructions there need to be updated.

BUG: The CreateNewExample will now work when ITK is not built as superbuild

---

src/Filtering/BinaryMathematicalMorphology/DilateABinaryImage/Code.cxx
src/Filtering/BinaryMathematicalMorphology/DilateABinaryImage/Code.py
src/Filtering/BinaryMathematicalMorphology/ErodeABinaryImage/Code.cxx
src/Filtering/BinaryMathematicalMorphology/ErodeABinaryImage/Code.py
src/Filtering/MathematicalMorphology/ErodeBinaryImageUsingFlatStruct/Code.cxx

The examples used default values that required the image
that was processed to only have values of 0 and 255.
The examples now explicitly set the foreground value of
255 to indicate that this may need to be set by the user
based on the data intensity values used as inputs.

DOC: Improve example to provide more complete usage

---

src/Core/Common/CMakeLists.txt
src/Core/Common/SetDefaultNumberOfThreads/CMakeLists.txt
src/Core/Common/SetDefaultNumberOfThreads/Code.cxx
src/Core/Common/SetDefaultNumberOfThreads/Code.py
src/Core/Common/SetDefaultNumberOfThreads/Documentation.rst
src/Core/Common/index.rst

Addresses: https://github.com/InsightSoftwareConsortium/ITK/issues/113

ENH: Add SetDefaultNumberOfThreads

---

Utilities/GitSetup/config

The GitSetup repo on public.kitware.com will be removed.

ENH: Point GitSetup to ITK repository

---

src/Developer/ImageFilter.h
src/Developer/ImageFilterMultipleOutputs.h
src/Developer/MyInPlaceImageFilter.h
src/Developer/itkImageFilterMultipleInputs.h
src/Developer/itkOilPaintingImageFilter.h
src/Numerics/Optimizers/AmoebaOptimizer/ExampleCostFunction.h

Deleting a function affects fundamental aspects of the client
interface of a class, and hiding them in private as if they
were implementation details is unhelpful.
Unfortunately, this was historically necessary for C++98, but no
longer required with C++11.
Co-authored-by: Hans Johnson  <hans-johnson@uiowa.edu>

STYLE: Prefer making deleted functions public

---

src/Filtering/ImageStatistics/AdaptiveHistogramEqualizationImageFilter/CMakeLists.txt
src/Filtering/ImageStatistics/CMakeLists.txt

AdaptiveHistogramEqualization is not availabel with the itk-5.1.0.post1
Python wrapping because an upgrade to Swig 4.0 causes segfault's during
swig execution with the AdaptiveHistogramEqualizationImageFilter module
wrapping.

BUG: Disable AdaptiveHistogramEqualization Python tests

---

Superbuild/External-VTK.cmake

The old URL, git protocol, is no longer supported.

BUG: Update VTK Git clone URL

---

src/Core/Common/GetImageSize/CMakeLists.txt
src/Core/Common/GetImageSize/Code.py
src/Core/Common/GetImageSize/Documentation.rst

Add Python code for `GetImageSize` example.

ENH: Add Python code for `GetImageSize` example

---

src/Core/Common/DuplicateAnImage/CMakeLists.txt
src/Core/Common/DuplicateAnImage/Code.py
src/Core/Common/DuplicateAnImage/Documentation.rst

Add Python code for `DuplicateAnImage` example.

ENH: Add Python code for `DuplicateAnImage` example

---

src/Core/Common/GetTypeBasicInformation/CMakeLists.txt
src/Core/Common/GetTypeBasicInformation/Code.py
src/Core/Common/GetTypeBasicInformation/Documentation.rst

Add Python code for `GetTypeBasicInformation` example.

ENH: Add Python code for `GetTypeBasicInformation` example

---

src/Core/Common/SetPixelValueInOneImage/CMakeLists.txt
src/Core/Common/SetPixelValueInOneImage/Documentation.rst
src/Core/common/SetPixelValueInOneImage/Code.py

Add Python code for `SetPixelValueInOneImage` example.

ENH: Add Python code for `SetPixelValueInOneImage` example

---

src/Core/Common/IterateRegionWithAccessToIndexWithWriteAccess/Code.cxx
src/Core/Common/IterateRegionWithAccessToIndexWithoutWriteAccess/Code.cxx

Fix pixel printing in `IterateRegionWithAccessToIndex` examples: cast the
pixel values to `int` to allow properly printing them.
The CI shows an unrecognized symbol, e.g. in build:
https://github.com/InsightSoftwareConsortium/ITKExamples/runs/895512782?check_suite_focus=true

BUG: Fix pixel printing in `IterateRegionWithAccessToIndex` examples

---

src/Core/Common/GetTypeBasicInformation/Documentation.rst
src/Core/Common/SetPixelValueInOneImage/Documentation.rst

Fix the Python code removal line limits to the appropriate values for each
example.

DOC: Fix the Python code removal line limits

---

src/Core/Common/CreateDerivativeKernel/Code.py
src/Core/Common/CreateForwardDifferenceKernel/CMakeLists.txt
src/Core/Common/CreateForwardDifferenceKernel/Code.py
src/Core/Common/CreateGaussianDerivativeKernel/Code.py
src/Core/Common/CreateGaussianKernel/Code.py
src/Core/Common/CreateLaplacianKernel/Code.py
src/Core/Common/DuplicateAnImage/Code.py
src/Core/Common/GetTypeBasicInformation/Code.py
src/Core/Common/SetPixelValueInOneImage/Code.py

Fix failing tests reported by CI, e.g. in this buid:
https://github.com/InsightSoftwareConsortium/ITKExamples/runs/895512782?check_suite_focus=true
Fixes:
- Convert the returned values of the calls to string so that they can be
printed properly in the kernel creation examples.
- Remove the brackets to get the `NumericTraits` attribute values in the
examples calling its attributes.
Take advantage of the commit to add the missing Python test for the
`CreateForwardDifferenceKernel` example.

BUG: Fix failing tests reported by CI

---

README.rst

Point `build, test` CI badge to builds: point to the `master` branch
status by default.

ENH: Point `build, test` CI badge to builds

---

src/Core/Common/GetImageSize/Code.py

The error was:
```text
55: Test command: "C:\Program Files\Python37\python.exe" "C:/Dev/ITKExamples/src/Core/Common/GetImageSize/Code.py" "C:/Dev/ITKExamples/Build/src/Core/Common/GetImageSize/Yinyang.png"
55: Test timeout computed to be: 1500
55: itkSize2 ([512, 342])
55: itkSize2 ([512, 342])
55: Traceback (most recent call last):
55:   File "C:/Dev/ITKExamples/src/Core/Common/GetImageSize/Code.py", line 40, in <module>
55:     print(image.shape)
55: AttributeError: 'itkImageUC2' object has no attribute 'shape'
1/1 Test #55: GetImageSizeTestPython ...........***Failed    2.68 sec
```

BUG: fix syntax error regarding shape attribute

---

src/Developer/ImageFilter.h
src/Developer/ImageFilterMultipleOutputs.h
src/Developer/MyInPlaceImageFilter.h
src/Developer/itkImageFilterMultipleInputs.h
src/Developer/itkOilPaintingImageFilter.h
src/Numerics/Optimizers/AmoebaOptimizer/ExampleCostFunction.h

This PR fixes changes made in [#2053](https://github.com/InsightSoftwareConsortium/ITK/pull/2053/commits/4eac1a0cfb456fad1e3894173a41d7c7de49b08f). Essentially, `ITK_DISALLOW_COPY_AND_ASSIGN` has been changed to `ITK_DISALLOW_COPY_AND_MOVE` to more accurately convey the actions taking place. `ITK_DISALLOW_COPY_AND_ASSIGN` will **only** be used if `ITK_FUTURE_LEGACY_REMOVE=OFF`.
**NOTE:** These changes will cause the GitHub Actions to break, because they currently build `ITK v5.1.0`. The errors persist with `v5.1.1` as well (will update to newest version in separate PR). When tested locally against `master`, I get all tests to pass. The case is the same for the remaining 39 remote modules.

STYLE: Rename ITK_DISALLOW_COPY_AND_ASSIGN to ITK_DISALLOW_COPY_AND_MOVE

---

src/Core/Common/CreateACovariantVector/CMakeLists.txt
src/Core/Common/CreateACovariantVector/Code.py
src/Core/Common/CreateACovariantVector/Documentation.rst
src/Core/Common/VectorDotProduct/CMakeLists.txt
src/Core/Common/VectorDotProduct/Code.py
src/Core/Common/VectorDotProduct/Documentation.rst

1. This example will do vector dot product arithmetic using itk's python package. In addition it will update the documentation and create a test.
**NOTE:** I import `double` from `numpy.core` to cast the output of `u * v`. If I don't do the cast (i.e. `str(u - (u * v) * v)` ), I get the following error:
```
TypeError: unsupported operand type(s) for *: 'float' and 'itkVectorD3'
```
2. The another example will create a `CovariantVector` object using itk's python package. In addition it will update the documentation and create a test.

ENH: Create Vector Dot Product and Covariant Vector Python Examples

---

.github/workflows/build-test.yml
Superbuild/External-ITK.cmake

Update ITK CI to reference ITK `master` branch as of 02-10-2021.

ENH: Update ITK CI tags to v5.2rc02

---

src/Core/Transform/CMakeLists.txt

[Issue 178](https://github.com/InsightSoftwareConsortium/ITKExamples/issues/178) is a blocking issue for checks on several outstanding PRs. This issue is related to the `MutualInformationAffine` test and baseline comparison, which passes locally but returns unsatisfactory results (see the [Mutual Information Affine example](https://itk.org/ITKExamples/src/Core/Transform/MutualInformationAffine/Documentation.html) and fails which executed remotely with GitHub Actions.
This PR disables building the offending examples to unblock outstanding PRs while the examples are updated.

BUG: Disable MutualInformationAffine example

---

Superbuild/External-OpenCV.cmake
src/Video/BridgeOpenCV/ConvertAnITKGrayScaleImageToCVMat/Code.cxx

This PR looks to bump the OpenCV version to `4.5.1` (the latest version). In addition, it looks to fix any warnings/errors that arose from the upgrade. This primarily required adjusting the included header files for `ConvertAnITKGrayScaleImageToCVMat`.
This will close #191 .

Superbuild OpenCV Upgrade

---

Documentation/Contribute/DashboardSubmission.rst
Documentation/Contribute/index.rst
Formatting/templates/indexcontent.html

Use Build Name instead of Group to obtain all GitHub Actions builds.

DOC: Fix dashboard link

---

.gitattributes
Superbuild/External-ClangFormat.cmake
Superbuild/ITKClangFormatConfig.cmake.in
Superbuild/Superbuild.cmake
Utilities/Hooks/pre-commit
Utilities/Hooks/pre-commit-style.bash

Infrastructure from ITK to run clang-format on C++ files during commit
to keep coding style consistent.

ENH: Add clang-format pre-commit hook

---

.github/workflows/lint.yml

To address:
reference is not a tree: 80fc7fe2e2de3d7c0a29bb3f0de7941f708ff5da
lint
Git checkout failed with exit code: 128
lint
Exit code 1 returned from process: file name '/home/runner/runners/2.277.1/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.
lint
Git checkout failed on shallow repository, this might because of git fetch with depth '1' doesn't include the checkout commit '80fc7fe2e2de3d7c0a29bb3f0de7941f708ff5da'.
lint
Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details, see actions/virtual-environments/issues/1816

BUG: Do not use shallow checkout for linting

---

Utilities/SphinxExtensions/RunGitStats.cmake.in

Update RunGitStats to require CMake 3.13.2 or greater - the same as
other ITK modules.

COMP: Bump min required version for CMake to > 2.8 to avoid warning

---

.github/workflows/build-test-publish.yml

Contrast and identify these builds with build-test-cxx and
build-test-notebooks: these builds use the superbuild, but in the
process they test the Python examples in addition to the C++ examples.

DOC: Rename build-test-superbuild to build-test-python

---

src/Filtering/ImageGrid/Create3DVolume/CMakeLists.txt

Small problem in filename which affected install of ITK with BUILD_EXAMPLES=ON.

Fix filename for Create3DVolume. 

---

src/Bridge/VtkGlue/ConvertAnRGBitkImageTovtkImageData/Code.py
src/Bridge/VtkGlue/ConvertAnitkImageTovtkImageData/Code.py

Require itk to be at least 5.2
In:
- ConvertAnRGBitkImageTovtkImageData
- ConvertAnitkImageTovtkImageData

ENH: Use itk.image_to_vtk_image if itk version is at least 5.2

---

src/IO/Mesh/ReadMesh/CMakeLists.txt

Another small doc fix.  Allows make install to complete when BUILD_EXAMPLES=ON in ITK.

Fix another small doc file

---

src/Registration/Metricsv4/RegisterTwoPointSets/Documentation.rst

I think the PR which introduced this example was concurrent to the one which swapped the order.

Switch to the new code order: Python before C++

---

Superbuild/External-Python.cmake

Addresses:
/home/matt/bin/ITKSphinxExamples-build/ITKEx-build/src/Registration/Common/MutualInformation/MutualInformation.ipynb:
WARNING: Pygments lexer name 'ipython3' is not known

BUG: Add ipython to Python environment for documentation build

---

src/Filtering/BinaryMathematicalMorphology/ThinImage/Code.py
src/Filtering/ImageIntensity/RescaleIntensity/Code.py
src/IO/ImageBase/WriteAnImage/Code.py

Note that the  corresponding .rst files has already accounted for the licensing block.

ENH: Added missing Python licensing files

---

src/IO/ImageBase/ReadAnImage/CMakeLists.txt
src/IO/ImageBase/ReadAnImage/Code.py
src/IO/ImageBase/ReadAnImage/Documentation.rst

Created a Python ReadAnImage example based off of the existing C++ example.

ENH: Added ReadAnImage Python script

---

src/Filtering/ImageFeature/LaplacianRecursiveGaussianImageFilter/CMakeLists.txt
src/Filtering/ImageFeature/LaplacianRecursiveGaussianImageFilter/Code.py
src/Filtering/ImageFeature/LaplacianRecursiveGaussianImageFilter/Documentation.rst

Created a Python LaplacianRecursiveGaussianImageFilter example based off of the existing C++ example.

ENH: Added LaplacianRecursiveGaussianImageFilter Python script

---

src/Numerics/Optimizers/ExhaustiveOptimizer/Code.cxx
src/Numerics/Statistics/ComputeHistogramFromGrayscaleImage/Code.cxx
src/Numerics/Statistics/ComputeHistogramOfMaskedRegion/Code.cxx
src/Numerics/Statistics/DistributionOfPixelsUsingGMM/Code.cxx
src/Registration/Common/ComputeMeanSquareBetweenTwoImages/Code.cxx
src/Registration/Common/GlobalRegistrationOfTwoImages/Code.cxx
src/Registration/Common/MatchFeaturePoints/Code.cxx
src/Registration/Common/MultiresolutionPyramidFromImage/Code.cxx
src/Registration/Common/MutualInformation/Code.cxx
src/Registration/Common/Perform2DTranslationRegistrationWithMeanSquares/Code.cxx
src/Registration/Common/PerformMultiModalityRegistrationWithMutualInformation/Code.cxx
src/Registration/Common/RegisterImageToAnotherUsingLandmarks/Code.cxx
src/Registration/Common/WatchRegistration/Code.cxx
src/Registration/Metricsv4/PerformRegistrationOnVectorImages/Code.cxx
src/Segmentation/Classifiers/ClusterPixelsInGrayscaleImage/Code.cxx
src/Segmentation/Classifiers/KMeansClusterOfPixelsInImage/Code.cxx
src/Segmentation/Classifiers/KMeansClustering/Code.cxx
src/Segmentation/ConnectedComponents/AssignContiguousLabelsToConnectedRegions/Code.cxx
src/Segmentation/ConnectedComponents/ExtraLargestConnectComponentFromBinaryImage/Code.cxx
src/Segmentation/ConnectedComponents/LabelConnectComponentsInBinaryImage/Code.cxx
src/Segmentation/ConnectedComponents/LabelConnectComponentsInGrayscaleImage/Code.cxx
src/Segmentation/KLMRegionGrowing/BasicRegionGrowing/Code.cxx
src/Segmentation/LabelVoting/IterativeHoleFilling/Code.cxx
src/Segmentation/LevelSets/SegmentWithGeodesicActiveContourLevelSet/Code.cxx
src/Segmentation/RegionGrowing/ConnectedComponentsInImage/Code.cxx
src/Segmentation/RegionGrowing/SegmentPixelsWithSimilarStats/Code.cxx
src/Segmentation/Voronoi/VoronoiDiagram/Code.cxx
src/Segmentation/Watersheds/MorphologicalWatershedSegmentation/Code.cxx
src/Segmentation/Watersheds/SegmentWithWatershedImageFilter/Code.cxx

Refs #226 in modules src/Registration, src/Segmentation, src/Numerics

STYLE: Use itk::ReadImage and itk::WriteImage in src/ Reg., Seg., Num.

---

.github/labeler.yml
.github/workflows/label-pr.yml
.github/workflows/lint.yml

Add labeler workflow so that a `GitHub` action, triggered when a PR is
opened, automatically labels the PR based on the given rules.

ENH: Add labeler workflow

---

src/Filtering/FFT/ComputeInverseFFTOfImage/Code.py

Previous behavior: FFT and baseline comparison sometimes returns NAN pixel values due to uninitialized buffer
Updated behavior: Pixels are initialized to 0; FFT and baseline comparison succeed

BUG: Initialize image buffer in Inverse FFT example

---

src/Core/Common/DistanceBetweenPoints/Code.cxx
src/Developer/ImageFilter.hxx
src/Developer/ImageFilterMultipleInputsDifferentType.hxx
src/Developer/ImageFilterMultipleOutputs.hxx
src/Developer/ImageFilterMultipleOutputsDifferentType.hxx
src/Developer/ImageFilterX.hxx
src/Developer/ImageFilterY.hxx
src/Developer/ImageSource.hxx
src/Developer/MultiThreadedImageFilter.hxx
src/Developer/MyInPlaceImageFilter.hxx
src/Developer/itkImageFilterMultipleInputs.hxx
src/Developer/itkOilPaintingImageFilter.hxx
src/Filtering/MathematicalMorphology/GenerateStructureElementsWithAccurateArea/Code.cxx

COMP: Remove inclusion of .hxx files as headers
The ability to include either .h or .hxx files as
header files required recursively reading the
.h files twice.  The added complexity is
unnecessary, costly, and can confuse static
analysis tools that monitor header guardes (due
to reaching the maximum depth of recursion
limits for nested #ifdefs in checking).

remove recursive header includes

---

.github/workflows/build-test-publish.yml

COMP: Modules need updated version of ITK
Removal of .h includes from same named .hxx files
requires removal of outdated rule that is no longer
relevant.
This PR will update the version of ITK that is
used for the remove modules."
BRANCH_NAME=update-reference-itk-version
for remdir_script in *.remote.cmake; do
remdir="${remdir_script//*.remote.cmake/}"
if [ ! -d "${remdir}" ] ;then
echo "Missing directory ${remdir}"
continue
fi
pushd "${remdir}" || exit
echo "=============== $(pwd) ========="
git checkout master
git fetch origin
git rebase origin/master
git checkout -b ${BRANCH_NAME}
sed 's/itk-git-tag : .*/itk-git-tag: "a89145bccda6a36f42cfdd45d3a6b27234ff54fe"/g' $( fgrep -Rl "itk-git-tag:" |fgrep yml )
git status
diff_line_no=$(git diff |wc -l )
if [ "${diff_line_no}" -ne 0 ]; then
git …

COMP: Modules need updated version of ITK

---

src/Developer/ImageFilter.h
src/Developer/ImageFilter.hxx
src/Developer/ImageFilterMultipleInputsDifferentType.h
src/Developer/ImageFilterMultipleInputsDifferentType.hxx
src/Developer/ImageFilterMultipleOutputs.h
src/Developer/ImageFilterMultipleOutputs.hxx
src/Developer/ImageFilterMultipleOutputsDifferentType.h
src/Developer/ImageFilterMultipleOutputsDifferentType.hxx
src/Developer/ImageFilterX.h
src/Developer/ImageFilterX.hxx
src/Developer/ImageFilterY.h
src/Developer/ImageFilterY.hxx
src/Developer/ImageSource.h
src/Developer/ImageSource.hxx
src/Developer/MultiThreadedImageFilter.h
src/Developer/MultiThreadedImageFilter.hxx
src/Developer/MyInPlaceImageFilter.h
src/Developer/MyInPlaceImageFilter.hxx
src/Developer/itkImageFilterMultipleInputs.h
src/Developer/itkImageFilterMultipleInputs.hxx
src/Developer/itkOilPaintingImageFilter.h
src/Developer/itkOilPaintingImageFilter.hxx

- BUG: Include the appropriate implementation file 
- BUG: Fix the class name in the `ImageSource` source files 
- BUG: Inherit `ImageSource` from ProcessObject`
- BUG: Make the include guards match the filenames 
- STYLE: Do not use double underscore defines 
- COMP: Use and move ITK_DISALLOW_COPY_AND_MOVE calls to public section
- STYLE: Move default construtor to .h
- STYLE: Prefer = default to explicitly trivial implementations
- COMP: Mark class destructors with `override`
- STYLE: Use typename instead of class in template definitions 
- ENH: Add `const` smart pointer type alias

ENH: Miscellaneous fixes to developer files

---

src/Core/Common/MultiThreadOilPainting/Code.cxx
src/Developer/OilPaintingImageFilter.cxx
src/Filtering/AnisotropicSmoothing/SmoothImageWhilePreservingEdges/Code.cxx
src/Filtering/AnisotropicSmoothing/SmoothImageWhilePreservingEdges2/Code.cxx
src/Filtering/BinaryMathematicalMorphology/PruneBinaryImage/Code.cxx
src/Filtering/CurvatureFlow/BinaryMinMaxCurvatureFlow/Code.cxx
src/Filtering/CurvatureFlow/SmoothImageUsingMinMaxCurvatureFlow/Code.cxx
src/Filtering/CurvatureFlow/SmoothRGBImageUsingCurvatureFlow/Code.cxx
src/Filtering/CurvatureFlow/SmoothRGBImageUsingMinMaxCurvatureFlow/Code.cxx
src/Filtering/ImageFeature/BilateralFilterAnImage/Code.cxx
src/Filtering/ImageFeature/SharpenImage/Code.cxx
src/Filtering/ImageFeature/ZeroCrossingBasedEdgeDecor/Code.cxx
src/Filtering/ImageGrid/RunImageFilterOnRegionOfImage/Code.cxx
src/Filtering/ImageIntensity/MaskImage/Code.cxx
src/Filtering/ImageIntensity/NormalizeImage/Code.cxx
src/Filtering/MathematicalMorphology/ErodeBinaryImageUsingFlatStruct/Code.cxx
src/Filtering/Thresholding/DemonstrateThresholdAlgorithms/Code.cxx
src/IO/ImageBase/RegisterIOFactories/CMakeLists.txt
src/Segmentation/ConnectedComponents/ExtraLargestConnectComponentFromBinaryImage/Code.cxx
src/Segmentation/ConnectedComponents/LabelConnectComponentsInBinaryImage/Code.cxx
src/Segmentation/RegionGrowing/SegmentPixelsWithSimilarStats/Code.cxx

Conditional code for ENABLE_QUICKVIEW no
longer compiled.
Changes to use simpler "auto image = ReadImage<>()"
function changed the signature of the variable type
for image.

COMP: ENABLE_QUICKVIEW code updates

---

CMake/DownloadDoxygenTAG.cmake
src/Filtering/ImageGrid/CropImageBySpecifyingRegion2/Code.cxx

Changes:
- Update DoxygenTAG.gz link to point to updated source at itk.org
- Fix RGB image init value in `CropImageBySpecifyingRegion2` example
~Resolves #324.~

BUG: Fixes for HTML documentation

---

.github/workflows/build-test-publish.yml

BUG: Ignore breathe duplicate C++ warnings in docs CI

---

.github/workflows/build-test-publish.yml

Linux documentation CI appears to build ITK both as a CI step and then again as a Superbuild step. This PR removes the initial CI step and relies solely on the Superbuild to speed up build time.
CI verifies that removing the earlier step does not impact build results.

ENH: Remove redundant ITK build step in docs CI

---

.fleek.json
.github/workflows/build-test-publish.yml

Continuing investigation into Fleek publish path issues.
Unfortunately we can only test Fleek publishing in the main branch. As publishing is currently failing this will not break anything, though it is not guaranteed to fix either. Moving ahead with merge.

ENH: Adjust site dir for Fleek container reference

---

.fleek.json
.github/workflows/build-test-publish.yml
Superbuild/External-ITK.cmake
Superbuild/External-Python.cmake
src/Registration/Metricsv4/RegisterTwoPointSets/CMakeLists.txt

BUG: Revert deploy to Netlify

---

CMake/DownloadDoxygen.cmake
CMake/DownloadDoxygenTAG.cmake
CMake/DownloadDoxygenXML.cmake

Workaround to address #362 by getting Doxygen archives for ITK v5.2.0 rather than latest nightly.

BUG: Use Doxygen 5.2.0 archives rather than nightly

---

src/Core/Common/CMakeLists.txt
src/Core/Common/ImageBufferAndIndexRange/CMakeLists.txt
src/Core/Common/ImageBufferAndIndexRange/Code.cxx
src/Core/Common/ImageBufferAndIndexRange/Documentation.rst
src/Core/Common/index.rst

Using `ImageBufferRange` and `IndexRange`, which were introduced with ITK 5.0.

ENH: Add `ImageBufferAndIndexRange` example

---

src/Core/Common/PrintModuleLoadingPython/CMakeLists.txt
src/Core/Common/PrintModuleLoadingPython/Code.py
src/Core/Common/PrintModuleLoadingPython/Documentation.rst
src/Core/Common/index.rst

ENH: Add Python example on module loading printouts

---

src/Core/Common/ImageBufferAndIndexRange/Documentation.rst

Following the guideline on how the write a title, at
https://examples.itk.org/documentation/contribute/writeanewexample#title
which suggests filling out the dots ("...") of the question, "How do I ...?"

DOC: Adjust title of `ImageBufferAndIndexRange` example

---

src/Core/Mesh/AccessDataInCells/CMakeLists.txt
src/Core/Mesh/AccessDataInCells/Code.cxx
src/Core/Mesh/AccessDataInCells/Code.py
src/Core/Mesh/AccessDataInCells/Documentation.rst
src/Core/Mesh/CMakeLists.txt
src/Core/Mesh/index.rst

blocker: identifiers beginning with a digit are not supported
```
File "./Code.py", line 29
CellTraits = itk.itkCellTraitsInfo.2FFULLULLULLPF2MCULLPF2
^
SyntaxError: invalid syntax
```

ENH: Translating Mesh3 C++ example into Python

---

src/Registration/Common/GlobalRegistrationOfTwoImages/CMakeLists.txt
src/Registration/Common/GlobalRegistrationOfTwoImages/Code.py

Created python version of the example for GlobalRegistrationOfTwoImages, including the CreateSphereImage and CreateEllipseImage functions. Produces same ellipse image, circle image, and output image as the C++ example

ENH: Add Python Example GlobalRegistrationOfTwoImages

---

.github/workflows/build-test-publish.yml

Switch Github Actions Linux environment version to `ubuntu-20.04`.
`ubuntu-18.04` is being deprecated and support will end by 12/1/2022:
https://github.com/actions/virtual-environments/issues/6002
Related to recent warnings in the Azure Pipelines Linux environment
being used in the main ITK repository:
https://github.com/InsightSoftwareConsortium/ITK/pull/3554/commits/497c3a7b8e1397ca56a2675ce846dca657af8861

ENH: Switch Github Actions Linux environment

---

.github/workflows/build-test-publish.yml

Switch Github Actions macOS environment version to `macos-11`.
`macOS-10.15` is being deprecated and support will end by 8/30/2022:
https://github.com/actions/virtual-environments/issues/5583
Related to recent warnings in the Azure Pipelines macOS environment
being used in the main ITK repository:
https://github.com/InsightSoftwareConsortium/ITK/pull/3532/commits/e5595dee1917e94ecc3c7f94873841b0f522d3c0

ENH: Switch Github Actions macOS environment

---

.github/labeler.yml

Fix the `Documentation`PR title identification: avoid having two entries for the `area:Documentation` label, and use the newly created `type:Documentation` for the PR title regex.

ENH: Fix the `Documentation` PR title identification

---

CMake/ITKSphinxExamplesMacros.cmake
src/Bridge/CMakeLists.txt
src/Core/CMakeLists.txt
src/Filtering/CMakeLists.txt
src/IO/CMakeLists.txt
src/Nonunit/CMakeLists.txt
src/Numerics/CMakeLists.txt
src/Registration/CMakeLists.txt
src/Remote/CMakeLists.txt
src/Segmentation/CMakeLists.txt
src/Video/CMakeLists.txt

Addresses issue where archives were not build for examples without an `add_example()` call, resulting in broken download links on `examples.itk.org`.
New behavior packages example archives for all examples to accompany Sphinx documentation. Also cleans up `CMakeLists.txt` for several module groups.
Closes #373.

ENH: Update CMake to decouple archives from example builds

---

src/Filtering/Thresholding/DemonstrateThresholdAlgorithms/Code.cxx

The error was:
```log
13>C:\Dev\ITKExamples\src\Filtering\Thresholding\DemonstrateThresholdAlgorithms\Code.cxx(77,14): error C2371: 'input': redefinition; different basic types
13>C:\Dev\ITKExamples\src\Filtering\Thresholding\DemonstrateThresholdAlgorithms\Code.cxx(57,14): message : see declaration of 'input'
13>C:\Dev\ITKExamples\src\Filtering\Thresholding\DemonstrateThresholdAlgorithms\Code.cxx(80,9): error C2672: 'QuickView::AddImage': no matching overloaded function found
13>C:\Dev\ITK-git\Modules\Bridge\VtkGlue\include\QuickView.h(128,3): message : could be 'void QuickView::AddImage(TImage *,bool,std::string)'
13>Done building project "DemonstrateThresholdAlgorithms.vcxproj" -- FAILED.
```

COMP: Remove duplicate image declaration and read

---

Documentation/Download/index.rst.in

These files are too large for Netlify.
Closes #397

BUG: Download HTML tarballs from GitHub Releases

---

.github/workflows/build-test-publish.yml
Superbuild/External-Python.cmake

To address #407, notebook CI error:
```
TraitError: label_image_weights shape expected to have 1 components, but got () components
```
Co-authored-by: Tom Birdsong <tom.birdsong@kitware.com>

COMP: Fix traitlets version to 5.6.0

---

Superbuild/CMakeLists.txt
Utilities/CookieCutter/{{cookiecutter.example_name}}/CMakeLists.txt
src/Core/Mesh/AccessDataInCells/CMakeLists.txt
src/Filtering/BinaryMathematicalMorphology/DilateABinaryImage/CMakeLists.txt

To be consistent with ITK 5.3.0.
Most of the other examples have already been updated.

COMP: Bump minimum CMake version to 3.16.3

---

ITKRepositoryImport.todo
src/Core/Transform/CMakeLists.txt
src/Core/Transform/DeformAVolumeWithAThinPlateSpline/CMakeLists.txt
src/Core/Transform/DeformAVolumeWithAThinPlateSpline/CheckerBoard.png.cid
src/Core/Transform/DeformAVolumeWithAThinPlateSpline/Code.cxx
src/Core/Transform/DeformAVolumeWithAThinPlateSpline/Code.py
src/Core/Transform/DeformAVolumeWithAThinPlateSpline/DeformedImage.png.cid
src/Core/Transform/DeformAVolumeWithAThinPlateSpline/DeformedImageBaseline.mha.cid
src/Core/Transform/DeformAVolumeWithAThinPlateSpline/Documentation.rst
src/Core/Transform/DeformAVolumeWithAThinPlateSpline/InputImage.png.cid
src/Core/Transform/DeformAVolumeWithAThinPlateSpline/SourceLandmarks.vtk.cid
src/Core/Transform/DeformAVolumeWithAThinPlateSpline/TargetLandmarks.vtk.cid
src/Core/Transform/DeformAVolumeWithAThinPlateSpline/brainweb165a10f17.mha.cid
src/Core/Transform/index.rst

Adapted from:
https://itk.org/Doxygen/html/Examples_2RegistrationITKv4_2ThinPlateSplineWarp_8cxx-example.html
However, we use itk mesh IO to read the point sets, and use the reference image interface to ResampleImageFilter. Both were added since that example was created.

ENH: Add DeformAVolumeWithAThinPlateSpline

---

src/Numerics/Statistics/CreateHistogramFromListOfMeasurements/Documentation.rst

Capitalize first letter for `Histogram` class name in index: avoids
creating a `histogram` entry linked to the same class name, and adds a
new link in the `Histogram` index entry.

STYLE: Capitalize first letter for `Histogram` class name in index

---

.github/workflows/build-test-publish.yml

Drop `treebeardtech/nbmake-action` and transition to `nbmake` to test notebooks: the former has been deprecated in favor of the latter.
See:
https://github.com/treebeardtech/nbmake-action
Fixes:
```
Node.js 12 actions are deprecated. For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16:
treebeardtech/nbmake-action@v0.2.1
```
raised for example in:
https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/actions/runs/3879592431

ENH: Transition to `nbmake` to test notebooks

---

.github/workflows/build-test-publish.yml
Superbuild/External-ITK.cmake
Superbuild/External-Python.cmake

The superbuild, python package and CI tests now use ITK 5.3 RC 3.

ENH: Bump ITK to 5.4 Release Candidate 3

---

.github/workflows/build-test-publish.yml

Bump `macOS` version to 10.13 in GHA build, test, publish workflow file.
Fixes:
```
GitHub Actions has encountered an internal error when running your job.
The macOS-12 environment is deprecated, consider switching to macOS-13, macOS-14 (macos-latest) or macOS-15.
For more details, see https://github.com/actions/runner-images/issues/10721
```
raised for example in:
https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/actions/runs/11671260757/job/32497243193

ENH: Bump `macOS` version to 10.13 in GHA build, test, publish

---

Formatting/conf.py.in

Specify the Read The Docs custom domain in the documentation config file.
Read the Docs is deprecating Sphinx context injection at build time starting Monday, Oct 7, 2024, so any custom domain specified in the Read the Docs admin needs to be defined in the configuration file.
Documentation:
https://about.readthedocs.com/blog/2024/07/addons-by-default/

STYLE: Specify ReadTheDocs custom domain configuration

---

src/Developer/ImageFilter.h
src/Developer/ImageFilterMultipleInputsDifferentType.h
src/Developer/ImageFilterMultipleOutputs.h
src/Developer/ImageFilterMultipleOutputsDifferentType.h
src/Developer/ImageFilterX.h
src/Developer/ImageFilterY.h
src/Developer/ImageSource.h
src/Developer/MultiThreadedImageFilter.h
src/Developer/MyInPlaceImageFilter.h
src/Developer/itkImageFilterMultipleInputs.h
src/Developer/itkOilPaintingImageFilter.h
src/Numerics/Optimizers/AmoebaOptimizer/ExampleCostFunction.h
src/Numerics/Optimizers/LevenbergMarquardtOptimization/itkExampleCostFunction.h

Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4373 commit https://github.com/InsightSoftwareConsortium/ITK/commit/2c264ea2ef62e916c6ef947599ce659cc8fce5fe "STYLE: Replace itkTypeMacro calls with `itkOverrideGetNameOfClassMacro`"
----
Assumes a very recent version of ITK (_after_ v5.4rc02), including commit https://github.com/InsightSoftwareConsortium/ITK/commit/94e7339da49a0cd3df6751f9e8a6e9ba91905dbd (merged to the ITK master branch on December 27, 2023)

COMP: Replace itkTypeMacro calls with `itkOverrideGetNameOfClassMacro`

---

CMake/DownloadDoxygen.cmake
CMake/DownloadDoxygenTAG.cmake
CMake/DownloadDoxygenXML.cmake
CMake/ITKDoxygen.cmake
CMake/ITKDoxygenTAG.cmake
CMake/ITKDoxygenXML.cmake

Note: This is intentionally not updated to the ITK source code version so we can bump the source version separately.

DOC: Update Doxygen XML for ITK 5.3.0

---

src/Core/Common/BoundingBoxOfAPointSet/Code.cxx
src/Core/Common/CreateAPointSet/Code.cxx
src/Core/Common/GenerateOffsetsShapedImageNeighborhood/Code.cxx
src/Core/Common/ReturnObjectFromFunction/Code.cxx
src/Core/Mesh/AccessDataInCells/Code.cxx
src/Core/Mesh/AddPointsAndEdges/Code.cxx
src/Core/Mesh/AddPointsAndEdges/Code.py
src/Core/Mesh/WriteMeshToVTP/Code.cxx
src/Filtering/ImageGrid/FitSplineIntoPointSet/Code.cxx

A few code improvements are indicated by clang-tidy and compiler warnings.

Compiler and clang-tidy cleanups

---

.github/workflows/build-test-publish.yml

Bump `upload-artifact` actions version to v4.
Fixes:
```
Artifact actions v3 will be closing down by January 30, 2025.
You are receiving this email because you have GitHub Actions
workflows using v3 of actions/upload-artifact or
actions/download-artifact. After this date using v3 of these
actions will result in a workflow failure.
```
received via email on Jan 7, 2025 from GitHub.

ENH: Bump `upload-artifact` actions version to v4
