InsightSoftwareConsortium/ITKSphinxExamples

- README.rst
Add the License badge to the ITK Examples GitHub home.
Change-Id: Iaeafe932c7449d007b5606511de4e119b0d53897
> DOC: Add the License badge.

- src/Core/Common/DoDataParallelThreading/Code.cxx
- src/Core/Common/ImportPixelBufferIntoAnImage/Code.cxx
- src/Core/Common/ObserveAnEvent/Code.cxx
- src/Core/Common/StreamAPipeline/Code.cxx
- src/Core/Common/TraceMemoryBetweenPoints/Code.cxx
- src/Core/Mesh/ExtractIsoSurface/Code.cxx
- src/Core/QuadEdgeMesh/CutMesh/Code.cxx
- src/Core/QuadEdgeMesh/ExtractVertexOnMeshBoundaries/Code.cxx
- src/Core/QuadEdgeMesh/PrintVertexNeighbors/Code.cxx
- src/Core/Transform/ApplyAffineTransformFromHomogeneousMatrixAndResample/Code.cxx
- src/Filtering/ImageGrid/ExtractRegionOfInterestInOneImage/Code.cxx
- src/Filtering/ImageIntensity/ComputeSigmoid/Code.cxx
- src/Filtering/ImageStatistics/ApplyAccumulateImageFilter/Code.cxx
- src/Filtering/LabelMap/ApplyMorphologicalClosingOnSpecificLabelObject/Code.cxx
- src/Filtering/LabelMap/ExtractGivenLabelObject/Code.cxx
- src/Filtering/LabelMap/MaskOneImageGivenLabelMap/Code.cxx
- src/Filtering/Thresholding/ThresholdAnImageUsingBinary/Code.cxx
- src/Filtering/Thresholding/ThresholdAnImageUsingOtsu/Code.cxx
- src/IO/GDCM/ReadDICOMSeriesAndWrite3DImage/Code.cxx
- src/IO/ImageBase/CreateAListOfFileNames/Code.cxx
- src/Numerics/Statistics/ComputeHistogramFromGrayscaleImage/Code.cxx
- src/Registration/Common/PerformMultiModalityRegistrationWithMutualInformation/Code.cxx
This pull request incorporates code changes
that happened in parallel with updating the
core ITK code to ITKv5 for C++11 conformity.
> ENH: Providing ITKv5 updates for C++11

- src/Segmentation/Watersheds/SegmentWithWatershedImageFilter/Code.py
adding the notes from the C++ to the python code so it is clearer what threshold and level mean
> Updating Watershed Python Code

- Documentation/Build/index.rst
- Documentation/Contribute/ContributeWithGit.rst
- Documentation/Contribute/index.rst
- Documentation/Download/index.rst.in
- README.rst
- Utilities/Dashboard/itkexamples_common.cmake
- itk-module.cmake
> ENH: Update Git clone URL's to point to GitHub

- src/Core/Common/UseParallelizeImageRegion/Documentation.rst
Also make grammar improvements.
> BUG: Fix CellsFluorescence1.png path in Use ParallelizeImageRegion

- src/CMakeLists.txt
CMake Error at src/CMakeLists.txt:26 (if):
if given arguments:
"LESS" "2.7"
Unknown arguments specified
> BUG: fixing CMake configure error

- src/Segmentation/Watersheds/SegmentWithWatershedImageFilter/Code.cxx
- src/Segmentation/Watersheds/SegmentWithWatershedImageFilter/Code.py
Fix `SegmentWithWatershedImageFilter` example `Code.cxx` C++ file
documentation error:
- Fix the executable name.
- Add the missing input arguments.
> DOC: Fix `SegmentWithWatershedImageFilter` example doc error.

- Utilities/Testing/azure-pipelines.yml
To address missing packages in python3-venv install.
> COMP: Run apt-get update in Linux Azure build

- src/Nonunit/Review/SegmentBloodVesselsWithMultiScaleHessianBasedMeasure/CMakeLists.txt
- src/Nonunit/Review/SegmentBloodVesselsWithMultiScaleHessianBasedMeasure/Code.py
- src/Nonunit/Review/SegmentBloodVesselsWithMultiScaleHessianBasedMeasure/Documentation.rst
Add `SegmentBloodVesselsWithMultiScaleHessianBasedMeasure` Python example
code.
> ENH: Add SegmentBloodVesselsWithMultiScaleHessianBasedMeasure Python code.

- README.rst
> DOC: Fix Azure pipeline badge.

- src/CMakeLists.txt
Hopefully will fix:
CMake Error at src/CMakeLists.txt:28 (if):
if given arguments:
"VERSION_LESS" "2.7"
Unknown arguments specified
https://open.cdash.org/viewBuildError.php?buildid=5854710
> ENH: fix configure error on faraway

- src/CMakeLists.txt
Compilation changes needed in cases of internal ITK build & SuperBuild scenarios.
Resolved target conflicts when building ITK/Examples and SphinxExamples.
> Fix itk internal build

- Superbuild/External-ITK.cmake
This has been merged into the ITKVtkGlue Remote Module for ITK 5.
> BUG: Do not enable Module_ITKLevelSetsv4Visualization

- Superbuild/External-Python.cmake
> BUG: Do not install pre-release Python packages in Superbuild

- Documentation/Build/index.rst
I corrected two typographical errors.
> Change DOCUMENATION to DOCUMENTATION in example

- src/Core/Common/CreateDerivativeKernel/CMakeLists.txt
- src/Core/Common/CreateDerivativeKernel/Code.py
- src/Core/Common/CreateDerivativeKernel/Documentation.rst
- src/Core/Common/CreateForwardDifferenceKernel/Code.py
- src/Core/Common/CreateForwardDifferenceKernel/Documentation.rst
- src/Core/Common/CreateGaussianDerivativeKernel/CMakeLists.txt
- src/Core/Common/CreateGaussianDerivativeKernel/Code.py
- src/Core/Common/CreateGaussianDerivativeKernel/Documentation.rst
- src/Core/Common/CreateGaussianKernel/CMakeLists.txt
- src/Core/Common/CreateGaussianKernel/Code.py
- src/Core/Common/CreateGaussianKernel/Documentation.rst
- src/Core/Common/CreateLaplacianKernel/CMakeLists.txt
- src/Core/Common/CreateLaplacianKernel/Code.py
- src/Core/Common/CreateLaplacianKernel/Documentation.rst
- src/Core/Common/CreateSobelKernel/CMakeLists.txt
- src/Core/Common/CreateSobelKernel/Code.py
- src/Core/Common/CreateSobelKernel/Documentation.rst
Add Python code for kernel creation examples.
> ENH: Add Python code for kernel creation examples

- .github/workflows/build-test.yml
- README.rst
Honor the workflows tasks: rename the workflow file and name to honor the
tasks being performend: there is no packaging.
> DOC: Honor the workflows tasks

- .github/workflows/build-test.yml
This PR updates the GitHub Actions with recent changes made to the `ITKModuleTemplate`.
> ENH: Update GitHub actions

- src/Registration/Metricsv4/CMakeLists.txt
- src/Registration/Metricsv4/RegisterTwoPointSets/CMakeLists.txt
- src/Registration/Metricsv4/RegisterTwoPointSets/Code.cxx
- src/Registration/Metricsv4/RegisterTwoPointSets/Code.py
- src/Registration/Metricsv4/RegisterTwoPointSets/Documentation.rst
Porting `itkJensenHavrdaCharvatTsallisPointSetMetricRegistrationTest` script from `ITK` repository as an example of point-to-point v4 registration.
(@thewtex )
> ENH: Add point set registration example

- Superbuild/External-Python.cmake
The newest version to support the latest manylinux version, etc.
> BUG: Upgrade pip in the superbuild virtual environment

- .github/workflows/build-test-publish.yml
- README.rst
Deploy previews and publish on master for https://itkexamples.netlify.app
Closes #159
> ENH: Add Netlify configuration

- src/Core/Transform/MutualInformationAffine/Documentation.rst
- src/Numerics/Optimizers/ExhaustiveOptimizer/Documentation.rst
- src/Registration/Common/MutualInformation/Documentation.rst
- src/Registration/Metricsv4/RegisterTwoPointSets/Documentation.rst
Make it easier to find. Use *Jupyter Notebook* consistently over
*Binder*.
> DOC: Place Jupyter Notebook section before Code

- src/Filtering/ImageGrid/ResampleAnImage/Code.py
- src/Filtering/ImageGrid/index.rst
- STYLE: Use Pythonic interface for ResampleAnImage
- DOC: Place resample examples next to each other in module index
> resample pythonic

- .github/workflows/build-test-publish.yml
- .github/workflows/lint.yml
- CMakeLists.txt
- Superbuild/External-ITK.cmake
Does not try to create an annotation, which is not permitted on forks
re: https://github.com/wearerequired/lint-action/issues/13
Addresses #234
> BUG: Use super-linter GitHub Action for black linting

- README.rst
- Superbuild/External-Python.cmake
- DOC: Add pandoc, nbsphinx to the documentation deps
- BUG: Add nbsphinx to the superbuild Python packages
> nbsphinx deps

- src/Core/Common/DistanceBetweenIndices/Documentation.rst
Change documentation section with the correct output.
> Update documentation output to match Code.cxx output

- src/Filtering/ImageGrid/ResampleAnImage/Code.py
Dashboard was red, but it is green with this one-line fix.
> BUG: Fix continuous integration failure of ResampleAnImage

- Documentation/Contribute/ContributeWithGit.rst
Explain what `example_name` and `class_name` are, as used in `CreateNewExample.py`.
> DOC: Add details for running CreateNewExample.py

- src/Filtering/ImageGrid/ResampleAnImage/Code.py
We no longer need: https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/pull/273
Following: https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/pull/275
> ENH: Simplify ResampleAnImage output parameters

- src/Filtering/BinaryMathematicalMorphology/ThinImage/CMakeLists.txt
- src/Filtering/BinaryMathematicalMorphology/ThinImage/Code.py
- src/Filtering/BinaryMathematicalMorphology/ThinImage/Documentation.rst
Created a Python ThinImage example based off of the existing C++ example.
> ENH: Added ThinImage Python script

- src/IO/ImageBase/WriteAnImage/CMakeLists.txt
- src/IO/ImageBase/WriteAnImage/Code.py
- src/IO/ImageBase/WriteAnImage/Documentation.rst
Created a Python WriteAnImage example based off of the existing C++ example.
> ENH: Added WriteAnImage Python script

- src/Filtering/ImageIntensity/RescaleIntensity/CMakeLists.txt
- src/Filtering/ImageIntensity/RescaleIntensity/Code.py
- src/Filtering/ImageIntensity/RescaleIntensity/Documentation.rst
Created a Python RescaleIntensity example based off of the existing C++ example.
> ENH: Added RescaleIntensity Python script

- src/Filtering/ImageFilterBase/ApplyKernelToEveryPixel/CMakeLists.txt
- src/Filtering/ImageFilterBase/ApplyKernelToEveryPixel/Code.py
- src/Filtering/ImageFilterBase/ApplyKernelToEveryPixel/Documentation.rst
Created a Python ApplyKernelToEveryPixel example based off of the existing C++ example.
> ENH: Added ApplyKernelToEveryPixel Python script

- src/Filtering/ImageCompare/CombineTwoImagesWithCheckerBoardPattern/CMakeLists.txt
- src/Filtering/ImageCompare/CombineTwoImagesWithCheckerBoardPattern/Code.py
- src/Filtering/ImageCompare/CombineTwoImagesWithCheckerBoardPattern/Documentation.rst
Created a Python CombineTwoImagesWithCheckerBoardPattern example based off of the existing C++ example.
> ENH: Added CombineTwoImagesWithCheckerBoardPattern Python script

- src/IO/ImageBase/CreateAListOfFileNames/CMakeLists.txt
- src/IO/ImageBase/CreateAListOfFileNames/Code.py
- src/IO/ImageBase/CreateAListOfFileNames/Documentation.rst
Created a Python CreateAListOfFileNames example based off of the existing C++ example.
> ENH: Added CreateAListOfFileNames Python script

- src/Filtering/FFT/ComputeInverseFFTOfImage/CMakeLists.txt
- src/Filtering/FFT/ComputeInverseFFTOfImage/Code.py
- src/Filtering/FFT/ComputeInverseFFTOfImage/Documentation.rst
Created a Python ComputeInverseFFTOfImage example based off of the existing C++ example.
> ENH: Added ComputeInverseFFTOfImage Python script

- src/Core/Transform/ScaleAnImage/Code.cxx
Hi,
I am aiming to contribute with #226. I have made an initial commit to test if I get the idea. I will go with major commits afterwards.
> STYLE: Use itk::WriteImage in ScaleAnImage

- src/Registration/Common/RegisterImageToAnotherUsingLandmarks/CMakeLists.txt
- src/Registration/Common/RegisterImageToAnotherUsingLandmarks/Code.cxx
- src/Registration/Common/RegisterImageToAnotherUsingLandmarks/Code.py
- src/Registration/Common/RegisterImageToAnotherUsingLandmarks/Documentation.rst
A few tweaks also to the C++ version.
> ENH: Add Python version of RegisterImageToAnotherUsingLandmarks

- src/Bridge/VtkGlue/ConvertAnRGBitkImageTovtkImageData/Code.py
- src/Bridge/VtkGlue/ConvertAnitkImageTovtkImageData/Code.py
Switched incorrect 'image_to_vtk_image' function call to the correct 'vtk_image_from_image'.
> BUG: Corrected VTK image from image conversion. 

- .github/workflows/build-test-publish.yml
Moving docs deployment to [Fleek](https://fleek.co/)
> ENH: Deploy docs to Fleek

- .github/workflows/build-test-publish.yml
I was a bit too trigger happy in #339 . Fixing CI variable.
> BUG: Fix github actions variable ref

- src/IO/ImageBase/ReadAnImage/Code.cxx
Follow-up to ITK pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2184
commit https://github.com/InsightSoftwareConsortium/ITK/commit/aeea88b1925e400fa6df099871b149a37f1dee17
"ENH: Add convenience function ReadImage", merged on 22 December 2020, and
included with ITK v5.2rc01
> STYLE: Simplify C++ example of ReadAnImage by calling `itk::ReadImage`

- src/Core/Common/CMakeLists.txt
- src/Core/Common/EagerModuleLoadingPython/CMakeLists.txt
- src/Core/Common/EagerModuleLoadingPython/Code.py
- src/Core/Common/EagerModuleLoadingPython/Documentation.rst
- src/Core/Common/index.rst
Short example partially addressing [https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/issues/356](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/issues/356)
> ENH: Add example on Python eager loading

- README.rst
3.16.3 following CMakeLists.txt.
> DOC: Update README required CMake version

- Formatting/conf.py.in
Provided by pydata-sphinx-theme.
> ENH: Add "Edit this page" links

- Formatting/conf.py.in
> DOC: Add GitHub repository icon link

- .github/workflows/build-test-publish.yml
- .github/workflows/lint.yml
- ENH: Fix workflow actions warnings linked to `Node.js`
- ENH: Bump `actions/upload-artifact` action to v3
> ENH: Fix workflow actions warnings linked to `Node.js`

- .github/workflows/build-test-publish.yml
- .github/workflows/lint.yml
- ENH: Use specific XCode version for GHA macOS 13 build
- ENH: Bump macOS version for notebook build, test GHA action step
- ENH: Bump checkout and setup-python GitHub actions versions
- ENH: Bump super-linter GitHub action version
> ENH: Fix macOS GHA toolchain
